version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strava-lens
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
