import Head from "next/head";
import { type ReactElement } from "react";
import MainLayout from "~/layout/MainLayout";
import Home from "~/modules/home/Home";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col w-full">
        <Home />
      </div>
    </>
  );
}

HomePage.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};
